### ISSUE TITLE
No ACF wysiwyg support or alternative

### ISSUE THREAD

**Issue by leroynijstad** [Recras/recras-wordpress-plugin#11]
Hello,

I'm having some problems with the plugin, the function that loads the online-booking.js and polyfills.js files will only be fired when there is shortcode inside the_content of a page.

But we are using ACF fields to fill the whole page and the default content is not used to show the form. Can u please add a hook or variable that lets you bypass the shouldIncludeLibrary() function inside the loadScripts function. 

Or an alternative to have a list of pages / post types inside the settings page of the Recras plugin. This way there is always an options to force the JS files to be enqueued

**Comment by Ugoku** [comment]
Hi Leroy,

thanks for your message. Your use case is a good point, we will think of something to make this work in the future and we will make this a priority!

**Comment by leroynijstad** [comment]
Hi Ugoku,

Thanks!

**Comment by Ugoku** [comment]
Fixed in [v 2.3.5](https://github.com/Recras/recras-wordpress-plugin/releases/tag/v2.3.5), thanks for reporting!
