### ISSUE TITLE
Contact form shows arrangements that don't belong to the form

### ISSUE THREAD

**Issue by Ugoku** [Recras/recras-wordpress-plugin#2]
Reproduce:
- have a contact form in Recras with certain arrangements selected, but not all
- in the plugin, use the shortcode to display this contact form

The form will show _all_ arrangements on the Recras instance, instead of only those supported by the form.

**Comment by timmipetit** [comment]
Came here to report this bug, but found out it was already reported :)

**Comment by Ugoku** [comment]
Needs to be tested (getting CORS errors here...) but should be fixed in master :)

**Comment by Ugoku** [comment]
Fixed in 1.1.0 !
