### ISSUE TITLE
Hoe werkt de product_amounts parameter in WordPress shortcodes?

### ISSUE THREAD

**Issue by ralphjsmit** [Recras/recras-wordpress-plugin#23]
Beste Recras, 

Ik ben voor een klant een WordPress website aan het integreren met Recras. Ik maak hiervoor gebruik van de Shortcodes voor online boekingen. Een van mijn stortcodes ziet er nu zo uit:

`[recras-booking use_new_library="1" package_list ="2,11" product_amounts="{ "2":"1", "11":1}" redirect="https://www.recras.com/contact/"]`

Nu heb ik een vraag over de `product_amounts` parameter. Hoe vul ik deze in? Als ik de parameter weglaat, geeft het formulier gelijk een error, omdat de standaardwaarde 0 is en de minimumwaarde 1. Ik wil dus dat de minimumwaarde altijd gelijk is aan 1. 

In de stortcode uitleg staat het volgende: 

> Pre-fill amounts - product_amounts, value is a valid JSON-object of line id's (as seen in the generated HTML) as keys and amounts as values. If you don't know what JSON is or how to find the line id's, contact your web developer.

Ik heb er nu dit van gemaakt:
`{ "2":"1", "11":1}`

Hiermee bedoel ik: arrangement met `id` 2 heeft standaard minimaal 1, evenals arrangement 11.

Kunnen jullie een voorbeeld geven van een JSON object die dit op de juiste manier implementeert?

Alvast dank!

**Comment by Ugoku** [comment]
Hallo Ralph,

elk arrangement heeft een aantal arrangementsregels. Neem bijvoorbeeld https://demo.recras.nl/onlineboeking?package=7 , daar zie je 3 regels. Via "Element inspecteren" kun je achter de ID's van de regels komen. Als er een of meerdere vaste regels zijn (boekingsgrootte), dan is er een element met ID `bookingsize` (ook in het bovengenoemde voorbeeld). De andere 2 regels hebben ID's 596 (`data-package-id`) en 597.
Deze moet je in je JSON-object gebruiken, dus bijv: `[recras-booking product_amounts='{"bookingsize": 12, "596": 8, "597": 4}']`. 
Let hierbij ook op het verschillende gebruik van `'` en `"`.

Groet,
Sander

**Comment by ralphjsmit** [comment]
Ha Sander, 

Dank voor je antwoord. Kan ik ook de standaard placeholder met booking size aanpassen?

Nu is dat bijvoorbeeld minimaal 10 stuks (zoals bij jouw demo). Standaard staat er echter '0' als placeholder en is het veld gelijk rood. Kan ik ook deze standaard op 10 stuks zetten, dat hij niet gelijk op rood/error staat?

**Comment by Ugoku** [comment]
De placeholder is niet aan te passen, maar je kunt het veld voor boekingsgrootte wel invullen op 10: `product_amounts='{"bookingsize": 10}'`

**Comment by ralphjsmit** [comment]
One top! Kan ik dit ook gebruiken met de `package_list` parameter? Dat ik voor elk package een andere booking size aangeef?

**Comment by Ugoku** [comment]
Sorry voor de late reactie. Dit werkt helaas alleen wanneer er exact 1 arrangement is geselecteerd, maar ik zal het intern eens voorleggen en wie weet kunnen we daar in de toekomst iets voor maken :)

**Comment by ralphjsmit** [comment]
Dankje!
