### ISSUE TITLE
Kan ik een 'product' ook laten bestellen bij online boekingen of alleen arrangementen?

### ISSUE THREAD

**Issue by ralphjsmit** [Recras/recras-wordpress-plugin#24]
Ik ben bezig met een online boekingen implementatie met Recras. Het formulier voor online boeken van een arrangement gaat  volgens mij goed. Nu vraag ik me af of ik ook producten kan laten boeken.

Neem bijv. een entree ticket. Deze staat in Recras aangegeven bij het kopje 'Producten'. Hoe vind ik het `id` van zo'n product en hoe gebruik ik dit met de `recras-booking` shortcode? Het liefst heb ik één formulier waarin zowel arrangementen als producten te boeken zijn.

**Boeken van meerdere arrangementen/producten**
Is het mogelijk om meerdere arrangementen en/of producten tegelijkertijd te laten boeken?
Dus bijv. entreetickets voor een x aantal personen plus een extra (horeca)product?

Dank!

**Comment by Ugoku** [comment]
We zijn hier momenteel mee bezig om dit mogelijk te maken. Dit is echter nog niet voor al onze leden openbaar. Als je hier gebruik van wilt maken kun je het beste even contact opnemen met Marthijn: marthijn@recras.nl

**Comment by ralphjsmit** [comment]
Oke, dankjewel!

Dan doe ik het voorlopig even zo via de arrangementen. Ik houd de releases in de gaten.
