### ISSUE TITLE
Plugin class not found after plugin activation

### ISSUE THREAD

**Issue by VanOnsNL** [Recras/recras-wordpress-plugin#31]
After activating the plugin it shows a fatal error:

**Fatal error:** Uncaught Error: Class 'Recras\Plugin' not found in /home/runcloud/webapps/wordpress/wp-content/plugins/recras/recras-wordpress-plugin.php:26

`Stack trace: #0 /home/runcloud/webapps/wordpress/wp-settings.php(409): include_once() 
#1 /home/runcloud/webapps/wordpress/wp-config.php(99): require_once('/home/runcloud/...') 
#2 /home/runcloud/webapps/wordpress/wp-load.php(50): require_once('/home/runcloud/...') 
#3 /home/runcloud/webapps/wordpress/wp-blog-header.php(13): require_once('/home/runcloud/...') 
#4 /home/runcloud/webapps/wordpress/index.php(17): require('/home/runcloud/...')
#5 {main} thrown in /home/runcloud/webapps/wordpress/wp-content/plugins/recras/recras-wordpress-plugin.php on line 26`

We've tested this with:
- Various custom themes
- WordPress 5.6.6 and 5.8.3
- Various plugins activated and everything deactivated
- Various servers and hosting providers

What is interesting is that the plugin keeps working on another website where the plugin has been active for several years and has been updated while active. Any new or existing WordPress installation where we try to activate the plugin results in the above mentioned fatal error.

Any help with this issue would be greatly appreciated!

**Comment by Ugoku** [comment]
Hi!

I have just tried to install (and activate) the plugin on a website that never had the plugin before, and it worked just fine. Can you share the following information?

- how did you install the plugin? (from the Plugins page in WP, downloaded from the plugins site and uploaded to the site, downloaded from GitHub, or something else)
- what version of PHP are you running?

Thanks!

**Comment by VanOnsNL** [comment]
Hi there!

Thanks for checking. In the meantime we did some more testing ourselves. The problem seems to be the require_once statement in _recras-wordpress-plugin.php_. 

Because there was no directory specified it included the autoloader in the root of our application folder, which exists because we use composer in our theme as well. It can be fixed by adding the plugin directory to the require statement:
`require_once(plugin_dir_path(__FILE__) . 'vendor/autoload.php');`

For now we'll add this to the plugin in our codebase. We hope it can be added in an upcoming update so we can keep updating the plugin in the future. :)

Thanks!

**Comment by Ugoku** [comment]
Thanks for the update! We will update this in our plugin. Can you please let us know if the pages from the Recras menu work as expected? They are also loaded through an `require_once` without a folder.

**Comment by VanOnsNL** [comment]
The settings pages do work in our application, but I think it would be wise to also specify the plugin directory for those. According to the PHP documentation, an include/require statement will first look for the folder in the root and if it is not found there try it in the directory where it was called. That's why the initial require_once in the plugin root file landed in our theme vendor folder. 

Reference: https://www.php.net/manual/en/function.include.php 

In our plugins we always define a few necessary constants in the root file, which we can use throughout the plugin. You could, for example, do something like this:

`## recras-wordpress-plugin.php`
`define('RECRAS_PLUGIN_DIR', plugin_dir_path(__FILE__));`
`require_once(RECRAS_PLUGIN_DIR . 'vendor/autoload.php');`

`## src/Settings.php`
`require_once(RECRAS_PLUGIN_DIR . 'src/admin/cache.php');`

This way you can be absolutely sure it always includes starting from the plugin directory.
